## Global Constants
BATCH_SIZE = 64
PRE_EPOCHS = 5
MOVING_AVERAGE_WINDOW_SIZE = 5

LENET_FREEZE_STEP = 1
RESNET_FREEZE_STEP = 2
MOBILENETV2_FREEZE_STEP = 3


# main.py
INITIAL_FREEZE_LAYERS = 1
LOSS_DIFF_THRESHOLD = 0.05

LOSS_DIFF_RATIO_THRESHOLD = 0.05

# trainer.py
LOSS_CONVERGED_THRESHOLD = 0.05
